language: python
python:
  - "2.7"
  - "3.6"
# Command to install dependencies
install:
  - sudo apt-get update
  - pip install -r requirements.txt

# Command to run tests
script:
  - pytest scripts/tests/*